// <auto-generated />
namespace login.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Zohaib : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Zohaib));
        
        string IMigrationMetadata.Id
        {
            get { return "201710121317469_Zohaib"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
